export const americanPhoneCodes = [
  { flag: '🇺🇸', code: '+1', currency: 'USD', label: 'Estados Unidos', iso: 'US' },
  { flag: '🇨🇦', code: '+1', currency: 'CAD', label: 'Canadá', iso: 'CA' },
  { flag: '🇲🇽', code: '+52', currency: 'MXN', label: 'México', iso: 'MX' },
  { flag: '🇨🇴', code: '+57', currency: 'COP', label: 'Colombia', iso: 'CO' },
  { flag: '🇻🇪', code: '+58', currency: 'VES', label: 'Venezuela', iso: 'VE' },
  { flag: '🇪🇨', code: '+593', currency: 'USD', label: 'Ecuador', iso: 'EC' },
  { flag: '🇵🇪', code: '+51', currency: 'PEN', label: 'Perú', iso: 'PE' },
  { flag: '🇧🇴', code: '+591', currency: 'BOB', label: 'Bolivia', iso: 'BO' },
  { flag: '🇨🇱', code: '+56', currency: 'CLP', label: 'Chile', iso: 'CL' },
  { flag: '🇦🇷', code: '+54', currency: 'ARS', label: 'Argentina', iso: 'AR' },
  { flag: '🇺🇾', code: '+598', currency: 'UYU', label: 'Uruguay', iso: 'UY' },
  { flag: '🇵🇾', code: '+595', currency: 'PYG', label: 'Paraguay', iso: 'PY' },
  { flag: '🇧🇷', code: '+55', currency: 'BRL', label: 'Brasil', iso: 'BR' },
];
