export const americanPhoneCodes = [
  { flag: "🇺🇸", code: "+1" },
  { flag: "🇨🇦", code: "+1" },
  { flag: "🇲🇽", code: "+52" },
  { flag: "🇨🇴", code: "+57" },
  { flag: "🇻🇪", code: "+58" },
  { flag: "🇪🇨", code: "+593" },
  { flag: "🇵🇪", code: "+51" },
  { flag: "🇧🇴", code: "+591" },
  { flag: "🇨🇱", code: "+56" },
  { flag: "🇦🇷", code: "+54" },
  { flag: "🇺🇾", code: "+598" },
  { flag: "🇵🇾", code: "+595" },
  { flag: "🇧🇷", code: "+55" },
];
