export const americanPhoneCodes = [
  { flag: '🇺🇸', code: '+1', currency: 'USD', label: 'Estados Unidos' },
  { flag: '🇨🇦', code: '+1', currency: 'CAD', label: 'Canadá' },
  { flag: '🇲🇽', code: '+52', currency: 'MXN', label: 'México' },
  { flag: '🇨🇴', code: '+57', currency: 'COP', label: 'Colombia' },
  { flag: '🇻🇪', code: '+58', currency: 'VES', label: 'Venezuela' },
  { flag: '🇪🇨', code: '+593', currency: 'USD', label: 'Ecuador' },
  { flag: '🇵🇪', code: '+51', currency: 'PEN', label: 'Perú' },
  { flag: '🇧🇴', code: '+591', currency: 'BOB', label: 'Bolivia' },
  { flag: '🇨🇱', code: '+56', currency: 'CLP', label: 'Chile' },
  { flag: '🇦🇷', code: '+54', currency: 'ARS', label: 'Argentina' },
  { flag: '🇺🇾', code: '+598', currency: 'UYU', label: 'Uruguay' },
  { flag: '🇵🇾', code: '+595', currency: 'PYG', label: 'Paraguay' },
  { flag: '🇧🇷', code: '+55', currency: 'BRL', label: 'Brasil' },
]
